heat_template_version: 2013-05-23

description: yaml file for region - region1

resources:
  nova_flavor:
    properties:
      disk: 12
      ephemeral: 0
      is_public: true
      ram: 4096
      rxtx_factor: 1
      swap: 0
      vcpus: 2
    type: OS::Nova::Flavor
